### ISSUE TITLE
[Zeroize] Breaking change for bounds

### ISSUE THREAD

**Issue by ETKNeil** [RustCrypto/utils#878]
Consider the following code
```rust
use zeroize::{Zeroize, ZeroizeOnDrop};

#[derive(zeroize::ZeroizeOnDrop, zeroize::Zeroize)]
pub struct Test<A: Marker> {
    #[zeroize(skip)]
    field: Option<A>,
}

pub trait Secret: ZeroizeOnDrop + Zeroize{}

impl<A:Marker> Secret for Test<A>{

}

pub trait Marker {}
```

This code used to compile with:
```toml
[dependencies]
zeroize = { version = "1", features = ["derive"] }
zeroize_derive = { version = "=1.3.3" }
```

But now by updating the derive
```toml
[dependencies]
zeroize = { version = "1", features = ["derive"] }
zeroize_derive = { version = "=1.4.0" }
```

I get
```sh
error[E0277]: the trait bound `Test<A>: Zeroize` is not satisfied
  --> src/lib.rs:11:16
   |
11 | impl<A:Marker> Secret for Test<A>{
   |                ^^^^^^ the trait `Zeroize` is not implemented for `Test<A>`
   |
note: required by a bound in `Secret`
  --> src/lib.rs:9:35
   |
9  | pub trait Secret: ZeroizeOnDrop + Zeroize{}
   |                                   ^^^^^^^ required by this bound in `Secret`
help: consider introducing a `where` clause, but there might be an alternative better way to express this requirement
   |
11 | impl<A:Marker> Secret for Test<A> where Test<A>: Zeroize{
   |                                   ++++++++++++++++++++++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `test_zeroize` due to previous error
```

Which is due to https://github.com/RustCrypto/utils/pull/858

I bisected and downgrading derive to 81536ee278943c128c033813227c3bd57639e20a works perfectly with my example, upgrading to syn v2 broke something

**Comment by ETKNeil** [comment]
If I would have to guess the change of logic in attr_skip/filter_skip is responsible, in particular in generate_fields I see a lot of logic change.

**Comment by tarcieri** [comment]
@ETKNeil can you confirm this was fixed by `zeroize_derive` v1.4.1?

**Comment by ETKNeil** [comment]
> @ETKNeil can you confirm this was fixed by `zeroize_derive` v1.4.1?

I confirm that 1.4.1 did fix it, thank you very much for reacting so quickly

**Comment by camshaft** [comment]
I am still seeing issues with v1.4.1 for the following code:

```rust
#[derive(Zeroize)]
pub struct Key<T>(T);
```

```
error[E0599]: the method `zeroize` exists for mutable reference `&mut T`, but its trait bounds were not satisfied
  --> src/lib.rs:53:10
   |
53 | #[derive(Zeroize)]
   |          ^^^^^^^^^^^^^^^^ method cannot be called on `&mut T` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `T: DefaultIsZeroes`
           which is required by `T: zeroize::Zeroize`
           `&mut T: DefaultIsZeroes`
           which is required by `&mut T: zeroize::Zeroize`
   = note: this error originates in the derive macro `zeroize::Zeroize` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This code is able to compile with `zeroize_derive` set to `v1.3.3`.

**Comment by tarcieri** [comment]
cc @maurer

**Comment by maurer** [comment]
Sorry about that, the where clauses I pulled out for the previous user shouldn't have been pulled out all the way. I've added another test for this side of things and am automatically generating Zeroize bounds for used fields now.

**Comment by tarcieri** [comment]
Released changes from #882 as `zeroize_derive` v1.4.2

**Comment by tarcieri** [comment]
@conradoplg it should work if a `where <C as Field>::Scalar: Zeroize` bound is added to the impl

**Comment by conradoplg** [comment]
> @conradoplg it should work if a `where <C as Field>::Scalar: Zeroize` bound is added to the impl

Indeed that works, I'm just curious about how it compiled without the bound before
